# DiffSensei-main/layout-generator/configs/infer.yaml
model:
  type: .layout_encoder.TokenLayoutEncoder  
  image_proj_model: "DiffSensei-main/checkpoints/diffsensei/image_generator/image_proj_model/pytorch_model.bin"
  pretrained_model_path: "model/stable-diffusion-xl-base-1.0"
  image_encoder_path: "IP-Adapter/models/image_encoder"
  magi_image_encoder_path: "DiffSensei-main/checkpoints/magi"
  planner_path: "/data/checkpoints/planner_step5000.pt"
  encoder:
    d_model:  512              # 256
    num_layers: 8              # 6
    num_heads:  8              # 8
    use_positional_encoding: true
    use_final_ln: true
    dropout: 0.05
  vision:
    num_ips: 6           # 角色最大数，采样用
    num_ip_sources: 1    # 每角色采样图片数
    num_vision_tokens: 16
    num_dummy_tokens: 16
    max_dialogs: 8
    
data:
  annotation_path: "/data/DiffSensei-main/layout-generator/checkpoints/f_annotations_style.json"
  image_dir: "DiffSensei-main/checkpoints/mangazero/images"

dataset:
  max_elements: 90
  max_panels: 30
  max_dialogs: 30
  max_characters: 30
  num_workers: 8
  batch_size: 64
  shuffle: true

resampler:
  dim: 1280
  depth: 4
  dim_head: 64
  heads: 20
  ff_mult: 4
  cross_attention_dim: 2048  
  
layout_types:
  TYPE_PAD: 0
  TYPE_PAGE: 1
  TYPE_PANEL: 2
  TYPE_CHAR: 3
  TYPE_DIALOG: 4

panel_shapes:
  panel_rect: {id: 0}
  panel_triangle: {id: 1}
  panel_trapezoid: {id: 2}
  panel_irregular_quad: {id: 3}

bubble_shapes:
  bubble_oval: {id: 0}
  bubble_flower: {id: 1}
  bubble_burst: {id: 2}
  bubble_rect: {id: 3}
