
model:
  type: .layout_encoder.LayoutTransformerEncoder
  parameters:
        used_condition_types: [
          'obj_class', 'obj_bbox', 'is_valid_obj'
        ]
        hidden_dim: 256
        output_dim: 1024 # model_channels x 4
        num_layers: 6
        num_heads: 8
        use_final_ln: True
        use_positional_embedding: False
        resolution_to_attention: [ 32, 16, 8 ]
        use_key_padding_mask: False

dataset:
  max_elements: 90     # 序列最大长度 (用于padding)
  used_condition_types: [ 'obj_class','obj_bbox' ]
  parameters:
    max_panels: 30       # 最大面板数
    max_dialogs: 30      # 最大对话数
    max_characters: 30   # 最大角色数
    filter_mode: 'LostGAN'
    image_size: 256
    layout_length: 10
    num_classes_for_layout_object: 185
    mask_size_for_layout_object: 32
    loader_num_workers: 4
    include_relationships: False
    instance_whitelist: null
    stuff_whitelist: null
    include_other: False
    min_object_size: 0.02
    min_objects_per_image: 1
    max_objects_per_image: 8
    stuff_only: True
    used_condition_types: [ 'obj_class','obj_bbox' ]
    return_origin_image: False
  train:
      data_path: "DiffSensei-main/checkpoints/mangazero/f_annotations_style.json"
      image_dir: "DiffSensei-main/checkpoints/mangazero/images"
      max_num_samples: null
      specific_image_ids: [ ]
      shuffle: True
      batch_size: 4           # 8 GPUs, total_batch_size=4x8=32

training:
  epochs: 100
  lr: 1e-4
  weight_decay: 0.01
  clip_grad_norm: 1.0
  lambda_style: 0.2         # 风格损失权重
  style_cfg_dropout: 0.1    # CFG 风格丢弃概率 p（训练时每样本独立丢弃风格）
  save_every: 1
  save_dir: "./checkpoints"