# DiffSensei-main/layout-generator/configs/train.yaml
model:
  type: .layout_encoder.TokenLayoutEncoder  
  image_proj_model: "DiffSensei-main/checkpoints/diffsensei/image_generator/image_proj_model/pytorch_model.bin"
  pretrained_model_path: "model/stable-diffusion-xl-base-1.0"
  image_encoder_path: "IP-Adapter/models/image_encoder"
  # image_encoder_path: "DiffSensei-main/checkpoints/diffsensei/image_generator/clip_image_encoder"
  # magi_image_encoder_path: "DiffSensei-main/checkpoints/diffsensei/image_generator/magi_image_encoder"
  magi_image_encoder_path: "DiffSensei-main/checkpoints/magi" 
  encoder:
    d_model:  512              # 256
    num_layers: 8              # 6
    num_heads:  8              # 8
    use_positional_encoding: true
    use_final_ln: true
    dropout: 0.05
  vision:
    num_ips: 10           # 角色最大数，采样用
    num_ip_sources: 1     # 每角色采样图片数
    num_vision_tokens: 16
    num_dummy_tokens: 16
    
data:
  annotation_path: "DiffSensei-main/checkpoints/mangazero/annotations_mask_5.json"
  image_dir: "DiffSensei-main/checkpoints/mangazero/images"

dataset:
  max_elements: 80
  max_panels: 19
  max_dialogs: 33
  max_characters: 28
  shuffle: false

training:
  num_workers: 4
  batch_size: 64
  epochs: 100
  lr: 1e-4
  weight_decay: 0.01
  clip_grad_norm: 1.0
  grad_clip_interval: 10  # 每多少 step 裁剪一次梯度
  log_interval: 10        # 每多少 step 记录一次到 TB
  lambda_style: 1.0
  lambda_geom: 5.0        # 需要调参
  style_mu: [0.9602522, 0.51703715, 0.45116463, 0.02762985]   # 预先计算了style params的均值和标准差用于归一化
  style_sigma: [0.14532684, 0.0966792,  0.13077953, 0.02751569]
  style_cfg_dropout: 0.05
  save_interval: 1000
  save_dir: "/data/DiffSensei-main/layout-generator/checkpoints/0906"
  resume_log_dir: "/data/DiffSensei-main/layout-generator/checkpoints/0906"
  gradient_accumulation_steps: 1
  mixed_precision: "fp16"
  seed: 42
  max_train_steps: 100000

resampler:
  dim: 1280
  depth: 4
  dim_head: 64
  heads: 20
  ff_mult: 4
  cross_attention_dim: 2048    # 新增，与预训练resampler权重一致
  
layout_types:
  TYPE_PAD: 0
  TYPE_PAGE: 1
  TYPE_PANEL: 2
  TYPE_CHAR: 3
  TYPE_DIALOG: 4

panel_shapes:
  panel_rect: {id: 0}
  panel_triangle: {id: 1}
  panel_trapezoid: {id: 2}
  panel_irregular_quad: {id: 3}

bubble_shapes:
  bubble_oval: {id: 0}
  bubble_flower: {id: 1}
  bubble_burst: {id: 2}
  bubble_rect: {id: 3}
